### ISSUE TITLE
T11.2 Crear BD (implementar)

### ISSUE THREAD

**Issue by 564786** [564786/SGA01#4]

**Comment by IVI-UNI** [comment]
Base de datos creada.
El siguiente paso será poblarla con datos de ejemplo.

**Comment by IVI-UNI** [comment]
Base de datos subida al servidor SQL server.
Sigue sin estar poblada.

**Comment by IVI-UNI** [comment]
La base de datos ya ha sido poblada con datos de ejemplo en cada tabla
